import { createApp } from 'vue'
import App from './App.vue'
import './styles.css'
import './picker.css'
import './workspace.css'
import './university.css'
import './role-landing.css'
import './search-select.css'
import './skills-page.css'
import './student-region.css'
import './auth.css'
import './admin.css'
import './student-insight.css'
import './pagination.css'
import './job-detail.css'

createApp(App).mount('#app')
